Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.provider "virtualbox"  do |vb|
	  vb.name = "Netology-Ubuntu"
	  vb.memory = "1024"
          vb.cpus = 1
	end
end


